# Generated by Django 5.0.4 on 2024-05-14 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["category_name"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["product_name"],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата производства продукта"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(
                help_text="Введите наименование категории",
                max_length=100,
                verbose_name="Наименование",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="descr",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="main.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="product",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="main/products/",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(
                help_text="Введите наименование продукта",
                max_length=100,
                verbose_name="Наименование",
            ),
        ),
    ]
