# Generated by Django 5.0.4 on 2024-05-14 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="manufactured_at",
        ),
    ]
